name: ci/cd [build and deploy libraries]

on: 
    workflow_dispatch:

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}

    steps:
      - name: Ensure ProGet NuGet Source
        run: |
          dotnet nuget add source ${{ vars.INMO_CICD_NUGET_FEED }} \
            -n kc \
            -u ${{ secrets.INMO_CICD_PROGET_USER }} \
            -p ${{ secrets.INMO_CICD_PROGET_PASS }} \
            --store-password-in-clear-text

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.15
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0.9.15
        with:
          useConfigFile: true

      - name: Set Version in Action Summary
        run: echo '### Semantic Version - ${{ steps.gitversion.outputs.fullSemVer }} ' >> $GITHUB_STEP_SUMMARY

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}

      - name: Run './build.cmd Install Generator'
        run: |
          ./build.cmd InstallGenerator \
            --helm-feed ${{ vars.INMO_CICD_HELM_FEED }} \
            --nuget-feed ${{ vars.INMO_CICD_NUGET_FEED }} \
            --pro-get-credentials ${{ secrets.PROGET_USER }}:${{ secrets.PROGET_PASSWORD }} \
            --pro-get-username ${{ secrets.PROGET_USER }} \
            --pro-get-password ${{ secrets.PROGET_PASSWORD }}
